version: "3.9"
services:
        nginx:
                depends_on: 
                       - "wordpress"
                build: 
                        context: "./requirements/nginx"
                        args:
                                UID: "${UID}"
                                GID: "${GID}"
                image: "nginx:1.22.1"
                container_name: "nginx"
                init: true
                restart: "unless-stopped"
                # command: sh # -- DUBUG --
                # stdin_open: true # -- DUBUG --
                # tty: true # -- DUBUG --
                ports:
                        - "443:443"
                environment:
                        DOMAIN_NAME: "${DOMAIN_NAME}"
                volumes:
                        - "wordpress:/var/www/wordpress"
                networks:
                        wordpressNetwork:
                                ipv4_address: "13.37.0.2"
        mariadb:
                build: 
                        context: "./requirements/mariadb"
                        args:
                                UID: "${UID}"
                                GID: "${GID}"
                image: "mariadb:10.6.10"
                container_name: "mariadb"
                init: true
                restart: "unless-stopped"
                # command: sh # -- DUBUG --
                # stdin_open: true # -- DUBUG --
                # tty: true # -- DUBUG --
                environment:
                        MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
                        MYSQL_USER: "${MYSQL_USER}"
                        MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
                        MYSQL_DATABASE: "${MYSQL_DATABASE}"
                volumes:
                        - "db:/var/lib/mysql"
                networks:
                        wordpressNetwork:
                                ipv4_address: "13.37.0.3"
        wordpress:
                depends_on:
                        - "mariadb"
                        - "redis"
                build: 
                        context: "./requirements/wordpress"
                        args:
                                UID: "${UID}"
                                GID: "${GID}"
                image: "wordpress:6.0.3"
                container_name: "wordpress"
                init: true
                restart: "unless-stopped"
                # command: sh # -- DUBUG --
                # stdin_open: true # -- DUBUG --
                # tty: true # -- DUBUG --
                environment:
                        WORDPRESS_DB_HOST: "mariadb"
                        WORDPRESS_DB_USER: "${MYSQL_USER}"
                        WORDPRESS_DB_PASSWORD: "${MYSQL_PASSWORD}"
                        WORDPRESS_DB_NAME: "${MYSQL_DATABASE}"
                        WORDPRESS_SITE_NAME: "${DOMAIN_NAME}"
                        WORDPRESS_SITE_TITLE: "${WORDPRESS_SITE_TITLE}"
                        WORDPRESS_ADMIN_NAME: "${WORDPRESS_ADMIN_NAME}"
                        WORDPRESS_ADMIN_PASSWORD: "${WORDPRESS_ADMIN_PASSWORD}"
                        WORDPRESS_ADMIN_EMAIL: "${WORDPRESS_ADMIN_EMAIL}"
                        WORDPRESS_USER_NAME: "${WORDPRESS_USER_NAME}"
                        WORDPRESS_USER_EMAIL: "${WORDPRESS_USER_EMAIL}"
                        WORDPRESS_USER_PASSWORD: "${WORDPRESS_USER_PASSWORD}"
                        WORDPRESS_USER_ROLE: "${WORDPRESS_USER_ROLE}"
                volumes:
                        - "wordpress:/var/www/wordpress"
                networks:
                        wordpressNetwork:
                                ipv4_address: "13.37.0.4"
        redis:
                build: 
                        context: "./requirements/bonus/redis"
                        args:
                                UID: "${UID}"
                                GID: "${GID}"
                image: "redis:7.0"
                container_name: "redis"
                init: true
                restart: "unless-stopped"
                # command: sh # -- DUBUG --
                # stdin_open: true # -- DUBUG --
                # tty: true # -- DUBUG --
                networks:
                        wordpressNetwork:
                                ipv4_address: "13.37.0.5"
        ftp:
                depends_on:
                        - "wordpress"
                build: 
                        context: "./requirements/bonus/ftp"
                        args:
                                UID: "${UID}"
                                GID: "${GID}"
                                FTP_USER_NAME: "${FTP_USER_NAME}"
                                FTP_USER_PASSWORD: "${FTP_USER_PASSWORD}"
                image: "ftp:3.0.5"
                container_name: "ftp"
                init: true
                restart: "unless-stopped"
                # command: sh # -- DUBUG --
                # stdin_open: true # -- DUBUG --
                # tty: true # -- DUBUG --
                ports:
                        - "20:20"
                        - "21:21"
                        - "20000-20010:20000-20010"
                volumes:
                        - "wordpress:/var/www/wordpress"
                networks:
                        ftpNetwork:
                                ipv4_address: "13.37.0.18"
        adminer:
                depends_on:
                        - "mariadb"
                build: 
                        context: "./requirements/bonus/adminer"
                        args:
                                UID: "${UID}"
                                GID: "${GID}"
                image: "adminer:4.8.1"
                container_name: "adminer"
                init: true
                restart: "unless-stopped"
                # command: sh # -- DUBUG --
                # stdin_open: true # -- DUBUG --
                # tty: true # -- DUBUG --
                networks:
                        wordpressNetwork:
                                ipv4_address: "13.37.0.6"
        portfolio:
                build: 
                        context: "./requirements/bonus/portfolio"
                        args:
                                UID: "${UID}"
                                GID: "${GID}"
                image: "portfolio:mannouao"
                container_name: "portfolio"
                init: true
                restart: "unless-stopped"
                # command: sh # -- DUBUG --
                # stdin_open: true # -- DUBUG --
                # tty: true # -- DUBUG --
                networks:
                        wordpressNetwork:
                                ipv4_address: "13.37.0.7"
        portainer:
                build: 
                        context: "./requirements/bonus/portainer"
                        args:
                                UID: "${UID}"
                                GID: "${GID}"
                                DGID: "${DGID}"
                image: "portainer:2.15.1"
                container_name: "portainer"
                init: true
                restart: "unless-stopped"
                # command: sh # -- DUBUG --
                # stdin_open: true # -- DUBUG --
                # tty: true # -- DUBUG --
                ports:
                        - "9443:9443"
                        - "8000:8000"
                networks:
                        portainerNetwork:
                                ipv4_address: "13.37.0.22"
                volumes:
                        - "portainerDB:/data"
                        - "/var/run/docker.sock:/var/run/docker.sock"
volumes:
        db:
                name: "db"
                driver: "local"
                driver_opts:
                        type: "none"
                        o: "bind"
                        device: "${HOME}/data/db"
        wordpress:
                name: "wordpress"
                driver: "local"
                driver_opts:
                        type: "none"
                        o: "bind"
                        device: "${HOME}/data/wordpress"
        portainerDB:
                name: "portainerDB"
                driver: "local"
                driver_opts:
                        type: "none"
                        o: "bind"
                        device: "${HOME}/data/portainerDB"
networks:
        wordpressNetwork:
                name: "wordpressNetwork"
                driver: "bridge"
                ipam:
                        config:
                                - subnet: "13.37.0.0/28"
        ftpNetwork:
                name: "ftpNetwork"
                driver: "bridge"
                ipam:
                        config:
                                - subnet: "13.37.0.16/30"
        portainerNetwork:
                name: "portainerNetwork"
                driver: "bridge"
                ipam:
                        config:
                                - subnet: "13.37.0.20/30"
