version: '3.9'
services:
        nginx:
                build: ./requirements/nginx
                image: nginx:1.22.0
                container_name:
                ports:
                        - "80:80"
