version : "3"

services:
        nginx:
                build: ./requirements/nginx
                image: nginx:1.22.0
                container_name: nginx
                ports:
                        - "443:443"
                environment:
                        - DOMAIN_NAME=${DOMAIN_NAME}

