version: "3.9"
services:
        nginx:
                depends_on: 
                        - "wordpress"
                build: "requirements/nginx"
                image: "nginx:1.22.0"
                container_name: "nginx"
                init: true
                restart: always
                #command: sh #--DEBUG--
                #stdin_open: true #--DEBUG--
                #tty: true #--DEBUG--
                ports:
                        - "443:443"
                environment:
                        DOMAIN_NAME: "${DOMAIN_NAME}"
                volumes:
                        - "wordpress:/var/www/wordpress"
                networks:
                        myNetwork:
                                ipv4_address: 172.20.0.2
        mariadb:
                build: "requirements/mariadb"
                image: "mariadb:10.6.9"
                container_name: "mariadb"
                init: true
                restart: always
                #command: sh #--DEBUG--
                #stdin_open: true #--DEBUG--
                #tty: true #--DEBUG--
                environment:
                        MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
                        MYSQL_USER: "${MYSQL_USER}"
                        MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
                        MYSQL_DATABASE: "${MYSQL_DATABASE}"
                volumes:
                        - "db:/var/lib/mysql"
                networks:
                        myNetwork:
                                ipv4_address: 172.20.0.3
        wordpress:
                depends_on:
                        - "mariadb"
                        - "redis"
                build: "requirements/wordpress"
                image: "wodpress:6.0.2"
                container_name: "wordpress"
                init: true
                restart: always
                #command: sh #--DEBUG--
                #stdin_open: true #--DEBUG--
                #tty: true #--DEBUG--
                environment:
                        WORDPRESS_DB_HOST: "mariadb"
                        WORDPRESS_DB_USER: "${MYSQL_USER}"
                        WORDPRESS_DB_PASSWORD: "${MYSQL_PASSWORD}"
                        WORDPRESS_DB_NAME: "${MYSQL_DATABASE}"
                        WORDPRESS_SITE_NAME: "${DOMAIN_NAME}"
                        WORDPRESS_SITE_TITLE: "${WORDPRESS_SITE_TITLE}"
                        WORDPRESS_ADMIN_NAME: "${WORDPRESS_ADMIN_NAME}"
                        WORDPRESS_ADMIN_PASSWORD: "${WORDPRESS_ADMIN_PASSWORD}"
                        WORDPRESS_ADMIN_EMAIL: "${WORDPRESS_ADMIN_EMAIL}"
                        WORDPRESS_USER_NAME: "${WORDPRESS_USER_NAME}"
                        WORDPRESS_USER_EMAIL: "${WORDPRESS_USER_EMAIL}"
                        WORDPRESS_USER_PASSWORD: "${WORDPRESS_USER_PASSWORD}"
                        WORDPRESS_USER_ROLE: "${WORDPRESS_USER_ROLE}"
                volumes:
                        - "wordpress:/var/www/wordpress"
                networks:
                        myNetwork:
                                ipv4_address: 172.20.0.4
        redis:
                build: "requirements/bonus/redis"
                image: "redis:7.0"
                container_name: "redis"
                init: true
                restart: always
                #command: sh #--DEBUG--
                #stdin_open: true #--DEBUG--
                #tty: true #--DEBUG--
                networks:
                        myNetwork:
                                ipv4_address: 172.20.0.5
        ftp:
                depends_on:
                        - "wordpress"
                build: "requirements/bonus/ftp"
                image: "ftp:3.0.5"
                container_name: "ftp"
                init: true
                restart: always
                #command: sh #--DEBUG--
                #stdin_open: true #--DEBUG--
                #tty: true #--DEBUG--
                ports:
                        - "20:20"
                        - "21:21"
                        - "21000:21010"
                environment:
                        FTP_USER_NAME: "${FTP_USER_NAME}"
                        FTP_USER_PASSWORD: "${FTP_USER_PASSWORD}"
                volumes:
                        - "wordpress:/var/www/wordpress"
        adminer:
                depends_on:
                        - "mariadb"
                build: "requirements/bonus/adminer"
                image: "adminer:4.8.1"
                container_name: "adminer"
                init: true
                restart: always
                #command: sh #--DEBUG--
                #stdin_open: true #--DEBUG--
                #tty: true #--DEBUG--
                networks:
                        myNetwork:
                                ipv4_address: 172.20.0.6
volumes:
        db:
                driver: "local"
                driver_opts:
                        type: "none"
                        o: "bind"
                        device: "/home/mannouao/data/db"
        wordpress:
                driver: "local"
                driver_opts:
                        type: "none"
                        o: "bind"
                        device: "/home/mannouao/data/wordpress"
networks:
        myNetwork:
                driver: "bridge"
                ipam:
                        config:
                                - subnet: 172.20.0.0/16
