version: '3.8'
services:
        nginx:
                build: ./requirements/nginx
                image: nginx:1.22.0
                container_name: nginx
                #                restart: always
                ports:
                        - "443:443"
                environment:
                        - DOMAIN_NAME=${DOMAIN_NAME}
