version: '3.8'
services:
        #nginx:
                #build: ./requirements/nginx
                #image: nginx:1.22.0
                #container_name: nginx
                #restart: always
                #ports:
                #       - "443:443"
                #environment:
                #       - DOMAIN_NAME=${DOMAIN_NAME}
        mariadb:
                build: ./requirements/mariadb
                image: mariadb
                container_name: mariadb
                restart: always
                stdin_open: true
                tty: true
                ports:
                        - "3306:3306"
                volumes:
                        - /home/mannouao/data/db:/var/lib/mysql
                environment:
                        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
                        - MYSQL_DATABASE=${MYSQL_DATABASE}
                        - MYSQL_USER=${MYSQL_USER}
                        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      #wordpress:
                #build: ./requirements/wordpress
                #image: wordpress
                #container_name: wordpress
                #restart: always
                #volumes:
                #        - /home/mannouao/data/wordpress:/var/www/html
                #environment:
                #        - WORDPRESS_DB_HOST=mariadb:3306
                #        - WORDPRESS_DB_USER=${MYSQL_USER}
                #        - WORDPRESS_DB_PASSWORD=${MYSQL_PASSWORD}
                #        - WORDPRESS_DB_NAME=${MYSQL_DATABASE}
